### ISSUE TITLE
Clipboard 0.20 and earlier broken on Macos Catalina

### ISSUE THREAD

**Issue by lbe** [shlomif/Clipboard#3]
Clipboard depends on Mac::Pasteboard for copy/paste functionality on Macos.  As of Macos Catalina, Clipboard versions 0.20 and earlier will use any version of Mac::Pasteboard.  Mac::Pasteboard versions earlier than 0.011 will not work on Macos Catalina.  v0.011 is the fist to support Macos Catalina.  

I have submitted Pull Request #2 with the only change of setting a minimum version for Mac::Pasteboard.

**Comment by shlomif** [comment]
resolved with a fix in the pull-req - closing
