### ISSUE TITLE
'Wide character in print' in Linux

### ISSUE THREAD

**Issue by shawnhcorey** [shlomif/Clipboard#4]
When using this module in Linux, copying UTF-8 strings results in a warning: Wide character in print...
This can be fixed by adding a `binmode` command after the open in `copy_to_selection`.

```
sub copy_to_selection {
    my $self = shift;
    my ($selection, $input) = @_;
    my $cmd = '|xclip -i -selection '. $selection;
    my $r = open my $exe, $cmd or die "Couldn't run `$cmd`: $!\n";
    binmode $exe, ':encoding(UTF-8)';
    print $exe $input;
    close $exe or die "Error closing `$cmd`: $!";

    return;
}

```

**Comment by shlomif** [comment]
Should be fixed in 0.26. Thanks for the report! Let me know if and when this ticket can be closed.

**Comment by shawnhcorey** [comment]
Got the update. Works good. Can close this.

**Comment by shlomif** [comment]
> Got the update. Works good. Can close this.

Thanks for the update. Closing then.
