### ISSUE TITLE
[feature] support more clipper: xsel, ...

### ISSUE THREAD

**Issue by Freed-Wu** [shlomif/Clipboard#9]
See <https://github.com/neovim/neovim/blob/db407010facc55c19b5ebdf881225ac39cb29d01/runtime/autoload/provider/clipboard.vim#L69-L158>

xclip is not the only clipper in linux. It should be not a depend but an optdepend. TIA!

```sh
❯ pacman -Qi perl-clipboard
Name            : perl-clipboard
Version         : 0.28-1
Description     : Perl clipboard module
Architecture    : any
URL             : https://metacpan.org/release/Clipboard
Licenses        : PerlArtistic  GPL
Groups          : None
Provides        : None
Depends On      : perl-cgi  perl-uri  xclip
Optional Deps   : None
Required By     : perl-app-nopaste
Optional For    : None
```

**Comment by shlomif** [comment]
Hi.

On Wed, 15 Mar 2023 20:13:11 -0700
wzy ***@***.***> wrote:

> See
> <https://github.com/neovim/neovim/blob/db407010facc55c19b5ebdf881225ac39cb29d01/runtime/autoload/provider/clipboard.vim#L69-L158>
> 
> xclip is not the only clipper in linux. It should be not a depend but an
> optdepend. TIA!
> 
> ```sh
> ❯ pacman -Qi perl-clipboard
> Name            : perl-clipboard
> Version         : 0.28-1
> Description     : Perl clipboard module
> Architecture    : any
> URL             : https://metacpan.org/release/Clipboard
> Licenses        : PerlArtistic  GPL
> Groups          : None
> Provides        : None
> Depends On      : perl-cgi  perl-uri  xclip
> Optional Deps   : None
> Required By     : perl-app-nopaste
> Optional For    : None
> ```
> 

1. pull-reqs / patches will be reviewed, and hopefully applied.

2. I have no control on the archlinux / manjaro / whatever's packages.

thanks!




-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/facts/Emma-Watson/

Larry Wall has more dollars in the bank than in his Perl code.
    — https://www.shlomifish.org/humour/bits/facts/Larry-Wall/

Please reply to list if it's a mailing list post - https://shlom.in/reply .
